import { dehydrate, QueryClient } from "@tanstack/query-core";
import { ContextContainer } from "./context-container";
import { getGreeting } from "../lib/queries/getGreeting";

import "./globals.css";

export const getData = async () => {
  const client = new QueryClient();

  await client.prefetchQuery(["greeting"], getGreeting);

  return dehydrate(client);
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const state = await getData();

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ContextContainer state={state}>{children}</ContextContainer>
      </body>
    </html>
  );
}
